give  Wed 15 Jul 10:54:08 AEST 2020: final

diff --git a/shrug-rm b/shrug-rm
--- a/shrug-rm
+++ b/shrug-rm
@@ -7,6 +7,12 @@ do
 done 
 i=$(($i - 1))
 
+if [ $i -eq -1 ] 
+then   
+    echo "shrug-rm: error: your repository does not have any commits yet"
+    exit 1
+fi
+
 force=0
 cached=0
 for file in $@
diff --git a/shrug-show b/shrug-show
--- a/shrug-show
+++ b/shrug-show
@@ -1,5 +1,11 @@
 #!/bin/dash
 
+if ! echo $1 | grep -q ":"
+then
+    echo "shrug-show: error: invalid object $1"
+    exit 1
+fi
+
 sub=$(echo $1 | grep [0-9]:[a-zA-Z0-9_.-]*)
 
 if [ -z $sub ]
